/* KIODEM — tresci w pieciu jezykach. Logika strony jest w app.js i nie zna tych tekstow.
   Kazdy tekst istnieje dla: en, pl, de, fr, es. Liczby w realizacjach sa wzgledne (ile razy,
   z ilu do ilu), nie kwotami klientow. */
window.KIODEM_DATA = (function () {
  "use strict";

  var LANGS = ["en", "pl", "de", "fr", "es"];

  var I18N = {
    en: {
      tagline: "Websites, automation and Google Ads for independent businesses.",
      hint: "Drag or scroll in any direction",
      "nav.work": "Work", "nav.services": "Services", "nav.about": "About", "nav.contact": "Contact", "nav.brief": "Brief",
      visit: "Visit the site", close: "Close",
      caseTech: "Under the hood", caseResult: "Measured", caseAdvice: "What I recommended",
      workLead: "Shops, clinics, schools and showrooms. Each one runs on its own numbers, so the work is judged by enquiries and sales, not by a launch.",
      servicesLead: "Five things, done by one person who also answers the phone.",
      aboutTitle: "About",
      aboutLead: "KIODEM is Michał Smoliński, working from Gliwice in southern Poland with clients in Poland, the United Kingdom and Germany.",
      about: [
        "The person you write to is the person who does the work. There is no account manager and no hand-off: the brief, the build and the numbers afterwards stay with one pair of hands.",
        "Scope is fixed and written in plain terms before anything starts. Accounts, domains and tracking are set up in your name, so nothing depends on me later.",
        "Most projects begin with a short written check of one journey on your site: how a customer gets from a search to an enquiry, and where that route breaks. It costs nothing and it tells both of us whether there is a project."
      ],
      facts: [["Based in", "Gliwice, Poland"], ["Working in", "English and Polish"], ["Clients in", "Poland, UK, Germany"], ["Platforms", "WordPress, WooCommerce, Shopify, Shoper, Shopware, plain HTML"], ["Measurement", "GA4, Tag Manager, Search Console, Merchant Center"]],
      contactTitle: "Contact", contactLead: "One email is enough. I reply within one working day.",
      mail: "michal@kiodem.com", phone: "+48 789 350 367", linkedin: "LinkedIn", write: "Write to me",
      contactNote: "Calls in English on weekdays 9 to 17 UK time. Or send the address of your site and I will come back with the short written check first.",
      contactBrief: "Or answer six questions and I will come back with a first take:",
      sections: { work: "Ten sites and shops, judged by enquiries", services: "Websites, search, ads, measurement, automation", about: "One person does the work you talk to", contact: "One email is enough", brief: "Six questions, two minutes, an answer from me" },
      brief: {
        intro: "Six questions, two minutes. The answer comes from me, not from a system.",
        steps: [
          { k: "who", type: "single", q: "What kind of business is it?", opts: ["Showroom or store", "Online shop", "Clinic or practice", "School or courses", "Services", "Something else"] },
          { k: "what", type: "multi", q: "What do you need?", hint: "Pick everything that applies.", opts: ["A website", "SEO and local search", "Google Ads", "Measurement", "Automation", "Not sure yet"] },
          { k: "state", type: "single", q: "Where are you now?", opts: ["Nothing online yet", "A site, but few enquiries", "Ads running, results unclear", "Growing, it has to hold"] },
          { k: "when", type: "single", q: "When?", opts: ["This month", "This quarter", "Just looking"] },
          { k: "site", type: "text", q: "Your website, if there is one", placeholder: "www.example.co.uk" },
          { k: "contact", type: "contact", q: "Where do I reply?", fields: [["name", "Name"], ["email", "Email"], ["company", "Company (optional)"], ["note", "Anything else (optional)"]] }
        ],
        labels: { who: "Business", what: "Needs", state: "Situation", when: "When", site: "Website", name: "Name", email: "Email", company: "Company", note: "Note" },
        next: "Next", back: "Back", review: "Review", send: "Send the brief", copy: "Copy the brief", copied: "Copied", edit: "Change answers", skip: "Skip",
        summaryTitle: "Your brief", sent: "Sent. I reply within one working day.",
        mailNote: "Your mail app opens with the brief filled in. If it does not, copy the brief and paste it into an email to",
        keyHint: "Number keys pick an answer, Enter continues.", emailError: "An email address is needed for the reply."
      }
    },
    pl: {
      tagline: "Strony, automatyzacje i Google Ads dla niezależnych firm.",
      hint: "Przeciągnij albo przewiń w dowolną stronę",
      "nav.work": "Realizacje", "nav.services": "Usługi", "nav.about": "O mnie", "nav.contact": "Kontakt", "nav.brief": "Brief",
      visit: "Zobacz stronę", close: "Zamknij",
      caseTech: "Od kuchni", caseResult: "Zmierzone", caseAdvice: "Co zarekomendowałem",
      workLead: "Sklepy, kliniki, szkoły i salony. Każda z tych firm działa na własnych liczbach, więc pracę ocenia się po zapytaniach i sprzedaży, nie po samym wdrożeniu.",
      servicesLead: "Pięć rzeczy, które robi jedna osoba. Ta sama, która odbiera telefon.",
      aboutTitle: "O mnie",
      aboutLead: "KIODEM to Michał Smoliński. Pracuję z Gliwic z klientami w Polsce, Wielkiej Brytanii i Niemczech.",
      about: [
        "Osoba, do której piszesz, jest osobą, która robi robotę. Bez opiekuna klienta i bez przekazywania dalej: brief, wdrożenie i liczby po wdrożeniu zostają w jednych rękach.",
        "Zakres jest ustalony i spisany zwykłym językiem, zanim cokolwiek się zacznie. Konta, domeny i pomiar zakładam na Ciebie, więc nic nie zależy ode mnie później.",
        "Większość projektów zaczyna się od krótkiego, pisemnego sprawdzenia jednej ścieżki na Twojej stronie: jak klient przechodzi od wyszukiwania do zapytania i gdzie ta droga się urywa. To nic nie kosztuje i mówi nam obojgu, czy jest tu projekt."
      ],
      facts: [["Siedziba", "Gliwice"], ["Języki", "polski i angielski"], ["Klienci", "Polska, Wielka Brytania, Niemcy"], ["Platformy", "WordPress, WooCommerce, Shopify, Shoper, Shopware, czysty HTML"], ["Pomiar", "GA4, Tag Manager, Search Console, Merchant Center"]],
      contactTitle: "Kontakt", contactLead: "Wystarczy jeden mail. Odpisuję w ciągu jednego dnia roboczego.",
      mail: "contact@kiodem.com", phone: "+48 789 350 367", linkedin: "LinkedIn", write: "Napisz do mnie",
      contactNote: "Rozmowy w dni robocze 9–17. Albo wyślij adres swojej strony, a najpierw odeślę krótkie pisemne sprawdzenie.",
      contactBrief: "Albo odpowiedz na sześć pytań, a wrócę z pierwszą oceną:",
      sections: { work: "Dziesięć stron i sklepów, ocenianych po zapytaniach", services: "Strony, wyszukiwarka, reklamy, pomiar, automatyzacje", about: "Robotę robi ta sama osoba, z którą rozmawiasz", contact: "Wystarczy jeden mail", brief: "Sześć pytań, dwie minuty, odpowiedź ode mnie" },
      brief: {
        intro: "Sześć pytań, dwie minuty. Odpowiedź przychodzi ode mnie, nie z systemu.",
        steps: [
          { k: "who", type: "single", q: "Jaka to firma?", opts: ["Salon lub sklep stacjonarny", "Sklep internetowy", "Klinika lub gabinet", "Szkoła lub kursy", "Usługi", "Coś innego"] },
          { k: "what", type: "multi", q: "Czego potrzebujesz?", hint: "Zaznacz wszystko, co pasuje.", opts: ["Strony", "SEO i wyszukiwania lokalnego", "Google Ads", "Pomiaru", "Automatyzacji", "Jeszcze nie wiem"] },
          { k: "state", type: "single", q: "Na jakim etapie jesteś?", opts: ["Nic jeszcze nie ma w sieci", "Jest strona, mało zapytań", "Reklamy działają, wyniki niejasne", "Rośniemy, ma to wytrzymać"] },
          { k: "when", type: "single", q: "Kiedy?", opts: ["W tym miesiącu", "W tym kwartale", "Na razie się rozglądam"] },
          { k: "site", type: "text", q: "Twoja strona, jeśli jest", placeholder: "www.przyklad.pl" },
          { k: "contact", type: "contact", q: "Gdzie mam odpisać?", fields: [["name", "Imię i nazwisko"], ["email", "E-mail"], ["company", "Firma (opcjonalnie)"], ["note", "Coś jeszcze (opcjonalnie)"]] }
        ],
        labels: { who: "Firma", what: "Potrzeby", state: "Etap", when: "Kiedy", site: "Strona", name: "Imię i nazwisko", email: "E-mail", company: "Firma", note: "Uwagi" },
        next: "Dalej", back: "Wstecz", review: "Podsumowanie", send: "Wyślij brief", copy: "Skopiuj brief", copied: "Skopiowane", edit: "Zmień odpowiedzi", skip: "Pomiń",
        summaryTitle: "Twój brief", sent: "Wysłane. Odpisuję w ciągu jednego dnia roboczego.",
        mailNote: "Otworzy się Twój program pocztowy z wypełnionym briefem. Jeśli nie, skopiuj brief i wklej go do maila na",
        keyHint: "Klawisze z cyframi wybierają odpowiedź, Enter idzie dalej.", emailError: "Do odpowiedzi potrzebny jest adres e-mail."
      }
    },
    de: {
      tagline: "Websites, Automatisierung und Google Ads für unabhängige Unternehmen.",
      hint: "Ziehen oder scrollen Sie in jede Richtung",
      "nav.work": "Arbeiten", "nav.services": "Leistungen", "nav.about": "Über mich", "nav.contact": "Kontakt", "nav.brief": "Briefing",
      visit: "Website ansehen", close: "Schließen",
      caseTech: "Unter der Haube", caseResult: "Gemessen", caseAdvice: "Meine Empfehlung",
      workLead: "Läden, Praxen, Schulen und Ausstellungsräume. Jedes dieser Unternehmen lebt von eigenen Zahlen, deshalb zählt am Ende die Anfrage und der Verkauf, nicht der Launch.",
      servicesLead: "Fünf Dinge, gemacht von einer Person, die auch ans Telefon geht.",
      aboutTitle: "Über mich",
      aboutLead: "KIODEM ist Michał Smoliński. Ich arbeite aus Gliwice im Süden Polens mit Kunden in Polen, Großbritannien und Deutschland.",
      about: [
        "Die Person, der Sie schreiben, ist die Person, die die Arbeit macht. Kein Kundenbetreuer, keine Übergabe: Briefing, Umsetzung und die Zahlen danach bleiben in einer Hand.",
        "Der Umfang steht fest und ist in klaren Worten aufgeschrieben, bevor etwas beginnt. Konten, Domains und Messung werden auf Ihren Namen eingerichtet, damit später nichts von mir abhängt.",
        "Die meisten Projekte beginnen mit einer kurzen schriftlichen Prüfung eines Weges auf Ihrer Website: wie ein Kunde von der Suche zur Anfrage kommt und wo dieser Weg abreißt. Das kostet nichts und zeigt uns beiden, ob es ein Projekt gibt."
      ],
      facts: [["Sitz", "Gliwice, Polen"], ["Sprachen", "Englisch und Polnisch, Deutsch schriftlich"], ["Kunden in", "Polen, Großbritannien, Deutschland"], ["Plattformen", "WordPress, WooCommerce, Shopify, Shoper, Shopware, reines HTML"], ["Messung", "GA4, Tag Manager, Search Console, Merchant Center"]],
      contactTitle: "Kontakt", contactLead: "Eine E-Mail genügt. Ich antworte innerhalb eines Werktags.",
      mail: "michal@kiodem.com", phone: "+48 789 350 367", linkedin: "LinkedIn", write: "Schreiben Sie mir",
      contactNote: "Telefonate auf Englisch an Werktagen von 9 bis 17 Uhr. Oder schicken Sie die Adresse Ihrer Website, dann kommt zuerst die kurze schriftliche Prüfung.",
      contactBrief: "Oder beantworten Sie sechs Fragen, und ich melde mich mit einer ersten Einschätzung:",
      sections: { work: "Zehn Websites und Shops, gemessen an Anfragen", services: "Websites, Suche, Anzeigen, Messung, Automatisierung", about: "Die Arbeit macht die Person, mit der Sie sprechen", contact: "Eine E-Mail genügt", brief: "Sechs Fragen, zwei Minuten, eine Antwort von mir" },
      brief: {
        intro: "Sechs Fragen, zwei Minuten. Die Antwort kommt von mir, nicht von einem System.",
        steps: [
          { k: "who", type: "single", q: "Was für ein Unternehmen ist es?", opts: ["Ausstellungsraum oder Laden", "Onlineshop", "Praxis oder Klinik", "Schule oder Kurse", "Dienstleistungen", "Etwas anderes"] },
          { k: "what", type: "multi", q: "Was brauchen Sie?", hint: "Wählen Sie alles, was zutrifft.", opts: ["Eine Website", "SEO und lokale Suche", "Google Ads", "Messung", "Automatisierung", "Noch unklar"] },
          { k: "state", type: "single", q: "Wo stehen Sie gerade?", opts: ["Noch nichts online", "Website da, wenig Anfragen", "Anzeigen laufen, Ergebnis unklar", "Wir wachsen, es muss halten"] },
          { k: "when", type: "single", q: "Wann?", opts: ["Diesen Monat", "Dieses Quartal", "Ich schaue mich nur um"] },
          { k: "site", type: "text", q: "Ihre Website, falls vorhanden", placeholder: "www.beispiel.de" },
          { k: "contact", type: "contact", q: "Wohin darf ich antworten?", fields: [["name", "Name"], ["email", "E-Mail"], ["company", "Firma (optional)"], ["note", "Noch etwas? (optional)"]] }
        ],
        labels: { who: "Unternehmen", what: "Bedarf", state: "Stand", when: "Wann", site: "Website", name: "Name", email: "E-Mail", company: "Firma", note: "Anmerkung" },
        next: "Weiter", back: "Zurück", review: "Zusammenfassung", send: "Briefing senden", copy: "Briefing kopieren", copied: "Kopiert", edit: "Antworten ändern", skip: "Überspringen",
        summaryTitle: "Ihr Briefing", sent: "Gesendet. Ich antworte innerhalb eines Werktags.",
        mailNote: "Ihr E-Mail-Programm öffnet sich mit dem ausgefüllten Briefing. Falls nicht, kopieren Sie es und senden es an",
        keyHint: "Zifferntasten wählen eine Antwort, Enter geht weiter.", emailError: "Für die Antwort brauche ich eine E-Mail-Adresse."
      }
    },
    fr: {
      tagline: "Sites web, automatisation et Google Ads pour les entreprises indépendantes.",
      hint: "Faites glisser ou défiler dans toutes les directions",
      "nav.work": "Réalisations", "nav.services": "Services", "nav.about": "À propos", "nav.contact": "Contact", "nav.brief": "Brief",
      visit: "Voir le site", close: "Fermer",
      caseTech: "Sous le capot", caseResult: "Mesuré", caseAdvice: "Ce que j'ai recommandé",
      workLead: "Boutiques, cliniques, écoles et showrooms. Chacune vit de ses propres chiffres : le travail se juge aux demandes et aux ventes, pas à la mise en ligne.",
      servicesLead: "Cinq choses, faites par une seule personne, celle qui répond aussi au téléphone.",
      aboutTitle: "À propos",
      aboutLead: "KIODEM, c'est Michał Smoliński. Je travaille depuis Gliwice, dans le sud de la Pologne, avec des clients en Pologne, au Royaume-Uni et en Allemagne.",
      about: [
        "La personne à qui vous écrivez est celle qui fait le travail. Pas de chargé de compte, pas de passage de relais : le brief, la réalisation et les chiffres qui suivent restent entre les mêmes mains.",
        "Le périmètre est fixé et écrit en termes simples avant de commencer. Les comptes, les domaines et la mesure sont créés à votre nom, pour que rien ne dépende de moi ensuite.",
        "La plupart des projets commencent par une courte vérification écrite d'un parcours sur votre site : comment un client passe de la recherche à la demande, et où ce chemin se casse. Cela ne coûte rien et nous dit à tous les deux s'il y a un projet."
      ],
      facts: [["Basé à", "Gliwice, Pologne"], ["Langues de travail", "anglais et polonais"], ["Clients en", "Pologne, Royaume-Uni, Allemagne"], ["Plateformes", "WordPress, WooCommerce, Shopify, Shoper, Shopware, HTML pur"], ["Mesure", "GA4, Tag Manager, Search Console, Merchant Center"]],
      contactTitle: "Contact", contactLead: "Un seul e-mail suffit. Je réponds sous un jour ouvré.",
      mail: "michal@kiodem.com", phone: "+48 789 350 367", linkedin: "LinkedIn", write: "M'écrire",
      contactNote: "Appels en anglais en semaine de 9 h à 17 h. Ou envoyez l'adresse de votre site et je reviendrai d'abord avec la courte vérification écrite.",
      contactBrief: "Ou répondez à six questions et je reviendrai avec un premier avis :",
      sections: { work: "Dix sites et boutiques, jugés aux demandes", services: "Sites, recherche, publicité, mesure, automatisation", about: "Le travail est fait par la personne à qui vous parlez", contact: "Un seul e-mail suffit", brief: "Six questions, deux minutes, une réponse de ma part" },
      brief: {
        intro: "Six questions, deux minutes. La réponse vient de moi, pas d'un système.",
        steps: [
          { k: "who", type: "single", q: "Quel type d'entreprise ?", opts: ["Showroom ou boutique", "Boutique en ligne", "Clinique ou cabinet", "École ou formations", "Services", "Autre chose"] },
          { k: "what", type: "multi", q: "De quoi avez-vous besoin ?", hint: "Cochez tout ce qui s'applique.", opts: ["Un site web", "SEO et recherche locale", "Google Ads", "Mesure", "Automatisation", "Pas encore sûr"] },
          { k: "state", type: "single", q: "Où en êtes-vous ?", opts: ["Rien en ligne pour l'instant", "Un site, mais peu de demandes", "Des annonces, résultats flous", "En croissance, ça doit tenir"] },
          { k: "when", type: "single", q: "Quand ?", opts: ["Ce mois-ci", "Ce trimestre", "Je regarde seulement"] },
          { k: "site", type: "text", q: "Votre site, s'il existe", placeholder: "www.exemple.fr" },
          { k: "contact", type: "contact", q: "Où puis-je répondre ?", fields: [["name", "Nom"], ["email", "E-mail"], ["company", "Entreprise (facultatif)"], ["note", "Autre chose ? (facultatif)"]] }
        ],
        labels: { who: "Entreprise", what: "Besoins", state: "Situation", when: "Quand", site: "Site", name: "Nom", email: "E-mail", company: "Entreprise", note: "Remarque" },
        next: "Suivant", back: "Retour", review: "Récapitulatif", send: "Envoyer le brief", copy: "Copier le brief", copied: "Copié", edit: "Modifier les réponses", skip: "Passer",
        summaryTitle: "Votre brief", sent: "Envoyé. Je réponds sous un jour ouvré.",
        mailNote: "Votre messagerie s'ouvre avec le brief rempli. Sinon, copiez le brief et collez-le dans un e-mail à",
        keyHint: "Les touches numériques choisissent une réponse, Entrée continue.", emailError: "Une adresse e-mail est nécessaire pour la réponse."
      }
    },
    es: {
      tagline: "Webs, automatización y Google Ads para negocios independientes.",
      hint: "Arrastra o desplaza en cualquier dirección",
      "nav.work": "Trabajos", "nav.services": "Servicios", "nav.about": "Sobre mí", "nav.contact": "Contacto", "nav.brief": "Brief",
      visit: "Ver el sitio", close: "Cerrar",
      caseTech: "Por dentro", caseResult: "Medido", caseAdvice: "Lo que recomendé",
      workLead: "Tiendas, clínicas, escuelas y salas de exposición. Cada una vive de sus propios números: el trabajo se juzga por consultas y ventas, no por el lanzamiento.",
      servicesLead: "Cinco cosas, hechas por una sola persona, la misma que contesta el teléfono.",
      aboutTitle: "Sobre mí",
      aboutLead: "KIODEM es Michał Smoliński. Trabajo desde Gliwice, en el sur de Polonia, con clientes en Polonia, Reino Unido y Alemania.",
      about: [
        "La persona a la que escribes es la que hace el trabajo. Sin gestor de cuentas ni traspasos: el brief, la construcción y los números posteriores quedan en las mismas manos.",
        "El alcance se fija y se escribe en lenguaje llano antes de empezar. Las cuentas, los dominios y la medición se crean a tu nombre, para que después nada dependa de mí.",
        "Casi todos los proyectos empiezan con una breve revisión escrita de un recorrido en tu web: cómo un cliente pasa de la búsqueda a la consulta y dónde se rompe ese camino. No cuesta nada y nos dice a los dos si hay proyecto."
      ],
      facts: [["Con base en", "Gliwice, Polonia"], ["Idiomas de trabajo", "inglés y polaco"], ["Clientes en", "Polonia, Reino Unido, Alemania"], ["Plataformas", "WordPress, WooCommerce, Shopify, Shoper, Shopware, HTML puro"], ["Medición", "GA4, Tag Manager, Search Console, Merchant Center"]],
      contactTitle: "Contacto", contactLead: "Basta con un correo. Respondo en un día laborable.",
      mail: "michal@kiodem.com", phone: "+48 789 350 367", linkedin: "LinkedIn", write: "Escríbeme",
      contactNote: "Llamadas en inglés en días laborables de 9 a 17 h. O envía la dirección de tu web y primero te devuelvo la breve revisión escrita.",
      contactBrief: "O responde seis preguntas y vuelvo con una primera valoración:",
      sections: { work: "Diez webs y tiendas, juzgadas por consultas", services: "Webs, búsqueda, anuncios, medición, automatización", about: "El trabajo lo hace la persona con la que hablas", contact: "Basta con un correo", brief: "Seis preguntas, dos minutos, una respuesta mía" },
      brief: {
        intro: "Seis preguntas, dos minutos. La respuesta viene de mí, no de un sistema.",
        steps: [
          { k: "who", type: "single", q: "¿Qué tipo de negocio es?", opts: ["Sala de exposición o tienda", "Tienda online", "Clínica o consulta", "Escuela o cursos", "Servicios", "Otra cosa"] },
          { k: "what", type: "multi", q: "¿Qué necesitas?", hint: "Marca todo lo que aplique.", opts: ["Una web", "SEO y búsqueda local", "Google Ads", "Medición", "Automatización", "Aún no lo sé"] },
          { k: "state", type: "single", q: "¿En qué punto estás?", opts: ["Todavía nada online", "Hay web, pocas consultas", "Anuncios activos, resultados confusos", "Creciendo, tiene que aguantar"] },
          { k: "when", type: "single", q: "¿Cuándo?", opts: ["Este mes", "Este trimestre", "Solo estoy mirando"] },
          { k: "site", type: "text", q: "Tu web, si la hay", placeholder: "www.ejemplo.es" },
          { k: "contact", type: "contact", q: "¿Dónde te respondo?", fields: [["name", "Nombre"], ["email", "Correo"], ["company", "Empresa (opcional)"], ["note", "¿Algo más? (opcional)"]] }
        ],
        labels: { who: "Negocio", what: "Necesidades", state: "Situación", when: "Cuándo", site: "Web", name: "Nombre", email: "Correo", company: "Empresa", note: "Nota" },
        next: "Siguiente", back: "Atrás", review: "Resumen", send: "Enviar el brief", copy: "Copiar el brief", copied: "Copiado", edit: "Cambiar respuestas", skip: "Saltar",
        summaryTitle: "Tu brief", sent: "Enviado. Respondo en un día laborable.",
        mailNote: "Se abrirá tu correo con el brief relleno. Si no, copia el brief y pégalo en un correo a",
        keyHint: "Las teclas numéricas eligen una respuesta, Intro continúa.", emailError: "Para responder necesito una dirección de correo."
      }
    }
  };

  /* Realizacje. `tech` = co zrobiono technicznie, `result` = co zmierzono (wzglednie),
     `advice` = co zarekomendowano. Pola opcjonalne. */
  var WORK = [
    { id: "electric-studio", name: "Electric Studio", url: "https://sklepelectricstudio.pl/", img: "electric-studio",
      sector: { en: "E-bike and e-moto shop, Poland", pl: "Sklep z e-rowerami i e-moto", de: "E-Bike- und E-Moto-Shop, Polen", fr: "Boutique de vélos et motos électriques, Pologne", es: "Tienda de bicis y motos eléctricas, Polonia" },
      what: { en: "Shop theme, product data, Google Ads with Merchant Center and supplier integrations for a Shoper store selling Surron, Talaria and E Ride Pro.",
              pl: "Szablon sklepu, dane produktów, Google Ads z Merchant Center i integracje z hurtowniami dla sklepu na Shoper z Surronami, Talarią i E Ride Pro.",
              de: "Shop-Theme, Produktdaten, Google Ads mit Merchant Center und Lieferantenanbindung für einen Shoper-Shop mit Surron, Talaria und E Ride Pro.",
              fr: "Thème de boutique, données produits, Google Ads avec Merchant Center et intégrations fournisseurs pour une boutique Shoper vendant Surron, Talaria et E Ride Pro.",
              es: "Plantilla de tienda, datos de producto, Google Ads con Merchant Center e integraciones con proveedores para una tienda Shoper que vende Surron, Talaria y E Ride Pro." },
      tech: { en: ["GA4 and Tag Manager rebuilt: the purchase event fired on every page view and inflated sales 280 times. One trigger condition fixed it.", "Supplier feeds and stock synced into the shop; product pages, instalment blocks and delivery dates generated from data.", "Search campaigns split by model, exact-match exclusions for bare brand names, search partners off, location targeting by presence."],
              pl: ["GA4 i Tag Manager przebudowane: zdarzenie zakupu strzelało na każdej odsłonie i zawyżało sprzedaż 280 razy. Naprawił to jeden warunek w wyzwalaczu.", "Feedy i stany hurtowni zsynchronizowane ze sklepem; karty produktów, bloki rat i terminy dostaw generowane z danych.", "Kampanie w wyszukiwarce podzielone po modelach, wykluczenia dokładne dla gołych nazw marek, partnerzy wyłączeni, geo po obecności."],
              de: ["GA4 und Tag Manager neu aufgesetzt: Das Kauf-Ereignis feuerte bei jedem Seitenaufruf und blähte die Verkäufe um das 280-Fache auf. Eine Trigger-Bedingung hat es behoben.", "Lieferanten-Feeds und Bestände mit dem Shop synchronisiert; Produktseiten, Ratenblöcke und Liefertermine aus Daten erzeugt.", "Suchkampagnen nach Modell getrennt, exakte Ausschlüsse für nackte Markennamen, Suchpartner aus, Standort nach Aufenthalt."],
              fr: ["GA4 et Tag Manager refaits : l'événement d'achat se déclenchait à chaque page vue et gonflait les ventes 280 fois. Une condition de déclencheur a suffi.", "Flux et stocks fournisseurs synchronisés avec la boutique ; fiches produits, blocs de paiement échelonné et délais de livraison générés à partir des données.", "Campagnes Search séparées par modèle, exclusions exactes des noms de marque seuls, partenaires de recherche désactivés, ciblage par présence."],
              es: ["GA4 y Tag Manager rehechos: el evento de compra saltaba en cada página vista e inflaba las ventas 280 veces. Lo arregló una condición en el activador.", "Feeds y stock de proveedores sincronizados con la tienda; fichas de producto, bloques de financiación y plazos de entrega generados desde los datos.", "Campañas de búsqueda separadas por modelo, exclusiones exactas de marcas a secas, partners de búsqueda apagados, ubicación por presencia."] },
      result: { en: ["Return on ad spend checked against paid orders, not the panel: the real figure was one eighth of what the dashboard showed.", "GA4 saw 68% of orders, the rest came in by phone. Since then every report carries two columns: measured and paid."],
                pl: ["Zwrot z reklam sprawdzony na opłaconych zamówieniach, nie w panelu: prawdziwa liczba była jedną ósmą tej z pulpitu.", "GA4 widziało 68% zamówień, reszta przychodziła telefonem. Od tej pory każdy raport ma dwie kolumny: zmierzone i opłacone."],
                de: ["Werbe-Rendite an bezahlten Bestellungen geprüft, nicht im Panel: Die echte Zahl war ein Achtel dessen, was das Dashboard zeigte.", "GA4 sah 68% der Bestellungen, der Rest kam per Telefon. Seitdem hat jeder Bericht zwei Spalten: gemessen und bezahlt."],
                fr: ["Retour sur dépenses publicitaires vérifié sur les commandes payées, pas dans le panneau : le chiffre réel valait un huitième de celui du tableau de bord.", "GA4 voyait 68% des commandes, le reste arrivait par téléphone. Depuis, chaque rapport a deux colonnes : mesuré et payé."],
                es: ["Retorno de la publicidad comprobado sobre pedidos pagados, no en el panel: la cifra real era una octava parte de la del cuadro de mando.", "GA4 veía el 68% de los pedidos, el resto llegaba por teléfono. Desde entonces cada informe lleva dos columnas: medido y pagado."] },
      advice: { en: ["Budget follows verified paid orders only. A pre-order page for the model whose searches double every month."],
                pl: ["Budżet idzie tylko za potwierdzonymi, opłaconymi zamówieniami. Strona pre-order dla modelu, którego wyszukiwania podwajają się co miesiąc."],
                de: ["Budget folgt nur geprüften, bezahlten Bestellungen. Eine Vorbestellseite für das Modell, dessen Suchanfragen sich monatlich verdoppeln."],
                fr: ["Le budget ne suit que les commandes payées et vérifiées. Une page de précommande pour le modèle dont les recherches doublent chaque mois."],
                es: ["El presupuesto sigue solo a los pedidos pagados y verificados. Una página de reserva para el modelo cuyas búsquedas se duplican cada mes."] } },
    { id: "rehamedica", name: "RehaMedica", url: "https://wprehamedica.com/", img: "rehamedica",
      sector: { en: "Physiotherapy clinic, Gliwice", pl: "Klinika fizjoterapii, Gliwice", de: "Physiotherapie-Praxis, Gliwice", fr: "Clinique de physiothérapie, Gliwice", es: "Clínica de fisioterapia, Gliwice" },
      what: { en: "WordPress website and hosting after a move from Framer, technical SEO, measurement and the Google Business Profile.",
              pl: "Strona na WordPressie i hosting po przejściu z Framera, SEO techniczne, pomiar i wizytówka Google.",
              de: "WordPress-Website und Hosting nach dem Wechsel von Framer, technisches SEO, Messung und Google-Unternehmensprofil.",
              fr: "Site WordPress et hébergement après une migration depuis Framer, SEO technique, mesure et fiche Google Business.",
              es: "Web en WordPress y alojamiento tras salir de Framer, SEO técnico, medición y perfil de Google Business." },
      tech: { en: ["Migration with 29 redirects so that no old address died.", "Booking routing for 85 price-list groups: every service leads to its own booking link or form. Before, most of them led to a dead end.", "Nine measured events with consent mode, no tracking on the symptom map and no service names in URLs, because health data has its own rules."],
              pl: ["Przenosiny z 29 przekierowaniami, żeby żaden stary adres nie umarł.", "Routing rezerwacji dla 85 grup cennika: każda usługa prowadzi do własnego linku rezerwacji albo formularza. Wcześniej większość kończyła się ślepą uliczką.", "Dziewięć mierzonych zdarzeń z trybem zgody, zero śledzenia na mapie dolegliwości i bez nazw usług w adresach, bo dane o zdrowiu mają własne reguły."],
              de: ["Umzug mit 29 Weiterleitungen, damit keine alte Adresse stirbt.", "Buchungs-Routing für 85 Preislistengruppen: Jede Leistung führt zu ihrem eigenen Buchungslink oder Formular. Vorher endeten die meisten in einer Sackgasse.", "Neun gemessene Ereignisse mit Consent Mode, kein Tracking auf der Beschwerdenkarte und keine Leistungsnamen in URLs, weil Gesundheitsdaten eigene Regeln haben."],
              fr: ["Migration avec 29 redirections pour qu'aucune ancienne adresse ne meure.", "Routage des réservations pour 85 groupes tarifaires : chaque prestation mène à son propre lien de réservation ou formulaire. Avant, la plupart finissaient dans une impasse.", "Neuf événements mesurés avec consent mode, aucun suivi sur la carte des symptômes et pas de noms de prestations dans les URL, parce que les données de santé ont leurs propres règles."],
              es: ["Migración con 29 redirecciones para que ninguna dirección antigua muriera.", "Enrutado de reservas para 85 grupos de la lista de precios: cada servicio lleva a su propio enlace de reserva o formulario. Antes, la mayoría acababa en un callejón sin salida.", "Nueve eventos medidos con modo de consentimiento, sin seguimiento en el mapa de síntomas y sin nombres de servicios en las URL, porque los datos de salud tienen sus propias reglas."] },
      advice: { en: ["A Business Profile run from the practice, not from an agency account, and a monthly read of Search Console by page."],
                pl: ["Wizytówka prowadzona z konta gabinetu, nie agencji, i comiesięczny odczyt Search Console po stronach."],
                de: ["Ein Unternehmensprofil, das aus der Praxis geführt wird, nicht aus einem Agenturkonto, und monatlich die Search Console nach Seiten."],
                fr: ["Une fiche Google gérée depuis la clinique, pas depuis un compte d'agence, et une lecture mensuelle de la Search Console par page."],
                es: ["Un perfil de Google gestionado desde la clínica, no desde una cuenta de agencia, y una lectura mensual de Search Console por página."] } },
    { id: "porto-alegre", name: "Porto Alegre", url: "https://portoalegre-gliwice.pl/", img: "porto-alegre",
      sector: { en: "Language school, Gliwice", pl: "Szkoła językowa, Gliwice", de: "Sprachschule, Gliwice", fr: "École de langues, Gliwice", es: "Escuela de idiomas, Gliwice" },
      what: { en: "SEO and Google Ads for a school where most sign-ups start with a phone call.",
              pl: "SEO i Google Ads dla szkoły, w której większość zapisów zaczyna się od telefonu.",
              de: "SEO und Google Ads für eine Schule, in der die meisten Anmeldungen mit einem Anruf beginnen.",
              fr: "SEO et Google Ads pour une école où la plupart des inscriptions commencent par un appel.",
              es: "SEO y Google Ads para una escuela donde casi todas las inscripciones empiezan con una llamada." },
      tech: { en: ["Call measurement from the site and from the ad: a call counts as an enquiry only after 40 seconds, so a tap on the number is no longer a lead.", "A forwarding number shown only to visitors from ads; organic visitors see the school's own number."],
              pl: ["Pomiar rozmów ze strony i z reklamy: rozmowa liczy się jako zapytanie dopiero po 40 sekundach, więc samo dotknięcie numeru nie jest już leadem.", "Numer przekierowujący widoczny tylko dla ruchu z reklam; wejścia organiczne widzą własny numer szkoły."],
              de: ["Anrufmessung von der Website und aus der Anzeige: Ein Anruf zählt erst ab 40 Sekunden als Anfrage, ein Tippen auf die Nummer ist kein Lead mehr.", "Eine Weiterleitungsnummer nur für Besucher aus Anzeigen; organische Besucher sehen die eigene Nummer der Schule."],
              fr: ["Mesure des appels depuis le site et depuis l'annonce : un appel ne compte comme demande qu'après 40 secondes, un simple appui sur le numéro n'est plus un lead.", "Un numéro de renvoi affiché uniquement aux visiteurs venus des annonces ; les visiteurs organiques voient le numéro de l'école."],
              es: ["Medición de llamadas desde la web y desde el anuncio: una llamada cuenta como consulta solo a partir de 40 segundos, así que tocar el número ya no es un lead.", "Un número de desvío visible solo para visitantes de anuncios; los orgánicos ven el número propio de la escuela."] },
      result: { en: ["Enquiries by phone and by form now sit in one report, by campaign."],
                pl: ["Zapytania telefoniczne i z formularza siedzą teraz w jednym raporcie, po kampaniach."],
                de: ["Anfragen per Telefon und per Formular stehen jetzt in einem Bericht, nach Kampagne."],
                fr: ["Les demandes par téléphone et par formulaire figurent désormais dans un seul rapport, par campagne."],
                es: ["Las consultas por teléfono y por formulario están ahora en un solo informe, por campaña."] },
      advice: { en: ["Move the primary conversion from the form to the call once two weeks of data confirm the pattern."],
                pl: ["Przenieść główną konwersję z formularza na rozmowę, gdy dwa tygodnie danych potwierdzą wzorzec."],
                de: ["Die Hauptkonversion vom Formular auf den Anruf verlegen, sobald zwei Wochen Daten das Muster bestätigen."],
                fr: ["Déplacer la conversion principale du formulaire vers l'appel dès que deux semaines de données confirment le schéma."],
                es: ["Pasar la conversión principal del formulario a la llamada cuando dos semanas de datos confirmen el patrón."] } },
    { id: "level", name: "LEVEL", url: "https://www.level.edu.pl/", img: "level",
      sector: { en: "Language school, three locations", pl: "Szkoła językowa, trzy filie", de: "Sprachschule, drei Standorte", fr: "École de langues, trois sites", es: "Escuela de idiomas, tres sedes" },
      what: { en: "Google Ads rebuilt around enquiries rather than clicks, SEO on Squarespace.",
              pl: "Google Ads przebudowane pod zapytania zamiast kliknięć, SEO na Squarespace.",
              de: "Google Ads neu aufgebaut um Anfragen statt Klicks, SEO auf Squarespace.",
              fr: "Google Ads reconstruit autour des demandes plutôt que des clics, SEO sur Squarespace.",
              es: "Google Ads reconstruido en torno a consultas y no a clics, SEO en Squarespace." },
      tech: { en: ["Search-term audit: eight of ten measured conversions came from people typing the school's own name. Generic terms produced none.", "Three campaigns, one per intent, exclusion lists of 165 competitor names and other towns, a cost-per-click ceiling instead of automated bidding on too little data."],
              pl: ["Audyt wyszukiwanych fraz: osiem z dziesięciu zmierzonych konwersji pochodziło od ludzi wpisujących nazwę szkoły. Frazy ogólne nie dały żadnej.", "Trzy kampanie, po jednej na intencję, listy wykluczeń ze 165 nazwami konkurencji i obcych miast, sufit kosztu kliknięcia zamiast automatu licytującego na zbyt małej próbie."],
              de: ["Suchbegriff-Audit: Acht von zehn gemessenen Konversionen kamen von Menschen, die den Namen der Schule eintippten. Generische Begriffe brachten keine.", "Drei Kampagnen, eine pro Absicht, Ausschlusslisten mit 165 Wettbewerbernamen und fremden Orten, eine Klickpreis-Obergrenze statt automatischer Gebote auf zu wenig Daten."],
              fr: ["Audit des termes de recherche : huit conversions mesurées sur dix venaient de gens tapant le nom de l'école. Les termes génériques n'en ont produit aucune.", "Trois campagnes, une par intention, des listes d'exclusion de 165 noms de concurrents et d'autres villes, un plafond de coût par clic au lieu d'enchères automatiques sur trop peu de données."],
              es: ["Auditoría de términos de búsqueda: ocho de cada diez conversiones medidas venían de gente que escribía el nombre de la escuela. Los términos genéricos no dieron ninguna.", "Tres campañas, una por intención, listas de exclusión con 165 nombres de competidores y otras ciudades, un tope de coste por clic en vez de pujas automáticas con pocos datos."] },
      result: { en: ["Clicks costing eight times the average stopped the day the ceiling went in. Cost per enquiry on the brand campaign is a fifth of the course campaign's.", "Two of six calls from ads went unanswered in working hours, and the report says so out loud."],
                pl: ["Kliknięcia po ośmiokrotności średniej skończyły się w dniu wprowadzenia sufitu. Koszt zapytania w kampanii markowej to jedna piąta kosztu w kampanii kursów.", "Dwie z sześciu rozmów z reklam nie zostały odebrane w godzinach pracy, i raport mówi to wprost."],
                de: ["Klicks zum Achtfachen des Durchschnitts hörten am Tag der Obergrenze auf. Die Kosten pro Anfrage der Markenkampagne sind ein Fünftel der Kurskampagne.", "Zwei von sechs Anrufen aus Anzeigen blieben zu Geschäftszeiten unbeantwortet, und der Bericht sagt das offen."],
                fr: ["Les clics à huit fois la moyenne se sont arrêtés le jour du plafond. Le coût par demande de la campagne de marque vaut un cinquième de celui de la campagne cours.", "Deux appels sur six venus des annonces sont restés sans réponse aux heures ouvrées, et le rapport le dit clairement."],
                es: ["Los clics a ocho veces la media se acabaron el día del tope. El coste por consulta de la campaña de marca es una quinta parte del de la campaña de cursos.", "Dos de seis llamadas desde anuncios quedaron sin contestar en horario laboral, y el informe lo dice claramente."] },
      advice: { en: ["More budget on the campaign that loses half its impressions to budget, not on the one that buys clicks."],
                pl: ["Więcej budżetu na kampanię, która traci połowę wyświetleń przez budżet, nie na tę, która kupuje kliknięcia."],
                de: ["Mehr Budget für die Kampagne, die die Hälfte ihrer Einblendungen durch Budget verliert, nicht für die, die Klicks kauft."],
                fr: ["Plus de budget sur la campagne qui perd la moitié de ses impressions faute de budget, pas sur celle qui achète des clics."],
                es: ["Más presupuesto para la campaña que pierde la mitad de sus impresiones por presupuesto, no para la que compra clics."] } },
    { id: "lepimy", name: "Lepimy", url: "https://pierogarnialepimy.pl/", img: "lepimy",
      sector: { en: "Pierogi restaurant, Gliwice", pl: "Pierogarnia, Gliwice", de: "Pierogi-Restaurant, Gliwice", fr: "Restaurant de pierogi, Gliwice", es: "Restaurante de pierogi, Gliwice" },
      what: { en: "Search review, page speed and the Google Business Profile for a restaurant that runs its site without cookies or banners.",
              pl: "Przegląd widoczności, szybkość strony i wizytówka Google dla restauracji, której strona działa bez ciasteczek i banerów.",
              de: "Sichtbarkeitsprüfung, Ladezeit und Google-Unternehmensprofil für ein Restaurant, dessen Website ohne Cookies und Banner läuft.",
              fr: "Revue de visibilité, vitesse de page et fiche Google pour un restaurant dont le site tourne sans cookies ni bandeaux.",
              es: "Revisión de visibilidad, velocidad y perfil de Google para un restaurante cuya web funciona sin cookies ni banners." },
      tech: { en: ["Largest Contentful Paint from 4.0 s to 2.9 s by taking the intro animation off the critical path; mobile performance score from 75 to 95.", "Structured data corrected: a review count that did not match reality was removed rather than left for Google to catch."],
              pl: ["Largest Contentful Paint z 4,0 s do 2,9 s po zdjęciu animacji wejścia ze ścieżki krytycznej; wynik wydajności mobile z 75 do 95.", "Dane strukturalne poprawione: liczba opinii niezgodna z rzeczywistością została usunięta, zamiast czekać, aż wyłapie ją Google."],
              de: ["Largest Contentful Paint von 4,0 s auf 2,9 s, indem die Intro-Animation vom kritischen Pfad genommen wurde; mobiler Performance-Score von 75 auf 95.", "Strukturierte Daten korrigiert: Eine Bewertungszahl, die nicht der Realität entsprach, wurde entfernt, statt darauf zu warten, dass Google sie findet."],
              fr: ["Largest Contentful Paint de 4,0 s à 2,9 s en sortant l'animation d'intro du chemin critique ; score de performance mobile de 75 à 95.", "Données structurées corrigées : un nombre d'avis qui ne correspondait pas à la réalité a été retiré plutôt que laissé à Google."],
              es: ["Largest Contentful Paint de 4,0 s a 2,9 s al sacar la animación de entrada de la ruta crítica; puntuación de rendimiento móvil de 75 a 95.", "Datos estructurados corregidos: un número de reseñas que no coincidía con la realidad se retiró en vez de esperar a que Google lo detectara."] },
      result: { en: ["Third place in the local pack for the main dish query, with a fifth of the reviews the two leaders have."],
                pl: ["Trzecie miejsce w pakiecie lokalnym na główne zapytanie o danie, przy jednej piątej opinii dwóch liderów."],
                de: ["Platz drei im Local Pack für die Hauptgerichts-Anfrage, mit einem Fünftel der Bewertungen der beiden Spitzenreiter."],
                fr: ["Troisième place dans le pack local sur la requête du plat principal, avec un cinquième des avis des deux leaders."],
                es: ["Tercer puesto en el pack local para la búsqueda del plato principal, con una quinta parte de las reseñas de los dos líderes."] },
      advice: { en: ["Reviews and photos on the Business Profile before any more code."],
                pl: ["Opinie i zdjęcia w wizytówce, zanim powstanie kolejna linia kodu."],
                de: ["Bewertungen und Fotos im Unternehmensprofil, bevor noch eine Zeile Code entsteht."],
                fr: ["Des avis et des photos sur la fiche Google avant la moindre ligne de code supplémentaire."],
                es: ["Reseñas y fotos en el perfil de Google antes de una línea más de código."] } },
    { id: "meume", name: "MEUME", url: "https://meumedesign.com/", img: "meume",
      sector: { en: "Furniture maker, Tychy", pl: "Producent mebli, Tychy", de: "Möbelhersteller, Tychy", fr: "Fabricant de mobilier, Tychy", es: "Fabricante de muebles, Tychy" },
      what: { en: "New WordPress website after the previous shop was cut off by its hosting, with WooCommerce and a configurator to follow.",
              pl: "Nowa strona na WordPressie po tym, jak hosting odciął poprzedni sklep; WooCommerce i konfigurator w kolejnych etapach.",
              de: "Neue WordPress-Website, nachdem der Hoster den alten Shop abgeschaltet hatte; WooCommerce und Konfigurator folgen.",
              fr: "Nouveau site WordPress après la coupure de l'ancienne boutique par l'hébergeur ; WooCommerce et configurateur à suivre.",
              es: "Nueva web en WordPress después de que el hosting cortara la tienda anterior; WooCommerce y configurador en las siguientes fases." },
      tech: { en: ["Classic theme with content editable in the admin, self-hosted fonts, no scroll hijacking.", "Content and product data recovered from the blocked site."],
              pl: ["Klasyczny motyw z treścią edytowalną w panelu, fonty na własnym serwerze, bez przejmowania przewijania.", "Treści i dane produktów odzyskane z zablokowanej strony."],
              de: ["Klassisches Theme mit im Backend bearbeitbaren Inhalten, selbst gehostete Schriften, kein Scroll-Hijacking.", "Inhalte und Produktdaten von der gesperrten Website gerettet."],
              fr: ["Thème classique avec contenu modifiable dans l'admin, polices auto-hébergées, pas de détournement du défilement.", "Contenus et données produits récupérés depuis le site bloqué."],
              es: ["Tema clásico con contenido editable en el panel, fuentes alojadas en el propio servidor, sin secuestro del scroll.", "Contenidos y datos de producto recuperados de la web bloqueada."] },
      advice: { en: ["Three stages, each usable on its own: pages first, shop second, configurator last."],
                pl: ["Trzy etapy, każdy użyteczny sam w sobie: najpierw strony, potem sklep, na końcu konfigurator."],
                de: ["Drei Etappen, jede für sich nutzbar: erst Seiten, dann Shop, zuletzt Konfigurator."],
                fr: ["Trois étapes, chacune utilisable seule : les pages d'abord, la boutique ensuite, le configurateur en dernier."],
                es: ["Tres fases, cada una útil por sí sola: primero las páginas, luego la tienda, al final el configurador."] } },
    { id: "gartendekor", name: "Gartendekor Lippstadt", url: "https://www.gartendekor-lippstadt.de/", img: "gartendekor",
      sector: { en: "Garden décor shop and showroom, Germany", pl: "Sklep i salon z dekoracjami ogrodowymi, Niemcy", de: "Gartendeko-Shop mit Ladengeschäft, Lippstadt", fr: "Boutique et showroom de décoration de jardin, Allemagne", es: "Tienda y exposición de decoración de jardín, Alemania" },
      what: { en: "Audit and Google Ads plan for a Shopware shop with a showroom.",
              pl: "Audyt i plan Google Ads dla sklepu na Shopware z salonem stacjonarnym.",
              de: "Audit und Google-Ads-Plan für einen Shopware-Shop mit Ladengeschäft.",
              fr: "Audit et plan Google Ads pour une boutique Shopware avec showroom.",
              es: "Auditoría y plan de Google Ads para una tienda Shopware con sala de exposición." },
      tech: { en: ["Twelve months of ads measured on a tracking tool that died in 2023: on paper a 0.02% conversion rate, in reality unknown.", "Eight Shopping campaigns losing up to 90% of impressions to budget; most spend in the month after the seasonal peak, and a fifth of it in winter at 15% of peak demand."],
              pl: ["Dwanaście miesięcy reklam mierzonych narzędziem, które umarło w 2023: na papierze współczynnik konwersji 0,02%, w rzeczywistości nieznany.", "Osiem kampanii Shopping tracących do 90% wyświetleń przez budżet; najwięcej wydane w miesiącu po szczycie sezonu, a jedna piąta zimą, przy 15% szczytowego popytu."],
              de: ["Zwölf Monate Anzeigen, gemessen mit einem Tool, das 2023 abgeschaltet wurde: auf dem Papier 0,02% Konversionsrate, in Wirklichkeit unbekannt.", "Acht Shopping-Kampagnen verlieren bis zu 90% der Einblendungen durch Budget; die meisten Ausgaben im Monat nach dem Saisonhöhepunkt, ein Fünftel im Winter bei 15% der Spitzennachfrage."],
              fr: ["Douze mois d'annonces mesurés avec un outil mort en 2023 : sur le papier un taux de conversion de 0,02%, en réalité inconnu.", "Huit campagnes Shopping perdant jusqu'à 90% des impressions faute de budget ; la plus grosse dépense le mois suivant le pic saisonnier, et un cinquième en hiver à 15% de la demande de pointe."],
              es: ["Doce meses de anuncios medidos con una herramienta que murió en 2023: sobre el papel una conversión del 0,02%, en realidad desconocida.", "Ocho campañas de Shopping perdiendo hasta el 90% de las impresiones por presupuesto; el mayor gasto el mes siguiente al pico de temporada y una quinta parte en invierno, con el 15% de la demanda máxima."] },
      result: { en: ["A budget curve that follows German search seasonality month by month, and two campaigns instead of eight."],
                pl: ["Krzywa budżetu idąca za niemiecką sezonowością wyszukiwań miesiąc po miesiącu i dwie kampanie zamiast ośmiu."],
                de: ["Eine Budgetkurve, die der deutschen Suchsaison Monat für Monat folgt, und zwei Kampagnen statt acht."],
                fr: ["Une courbe de budget qui suit la saisonnalité des recherches allemandes mois par mois, et deux campagnes au lieu de huit."],
                es: ["Una curva de presupuesto que sigue la estacionalidad de búsqueda alemana mes a mes, y dos campañas en vez de ocho."] },
      advice: { en: ["Measurement first, then a comparison with real orders and calls, then the catalogue. A platform change is a security decision, not an SEO one."],
                pl: ["Najpierw pomiar, potem zestawienie z prawdziwymi zamówieniami i telefonami, potem katalog. Zmiana platformy to decyzja o bezpieczeństwie, nie argument SEO."],
                de: ["Erst Messung, dann der Abgleich mit echten Bestellungen und Anrufen, dann der Katalog. Ein Plattformwechsel ist eine Sicherheitsentscheidung, kein SEO-Argument."],
                fr: ["La mesure d'abord, puis une comparaison avec les vraies commandes et les appels, puis le catalogue. Changer de plateforme est une décision de sécurité, pas un argument SEO."],
                es: ["Primero la medición, luego la comparación con pedidos y llamadas reales, luego el catálogo. Cambiar de plataforma es una decisión de seguridad, no un argumento SEO."] } },
    { id: "voltgo", name: "VoltGo", url: "https://voltgo.pl/", img: "voltgo",
      sector: { en: "Electric vehicle rental marketplace", pl: "Marketplace wypożyczalni pojazdów elektrycznych", de: "Marktplatz für E-Fahrzeug-Vermietung", fr: "Place de marché de location de véhicules électriques", es: "Marketplace de alquiler de vehículos eléctricos" },
      what: { en: "Catalogue work on a custom CMS: vehicle versions, pricing and photos for rental stations.",
              pl: "Prace katalogowe na autorskim CMS: wersje pojazdów, cenniki i zdjęcia dla wypożyczalni.",
              de: "Katalogarbeit in einem eigenen CMS: Fahrzeugversionen, Preise und Fotos für Vermietstationen.",
              fr: "Travail de catalogue sur un CMS maison : versions de véhicules, tarifs et photos pour les stations de location.",
              es: "Trabajo de catálogo en un CMS propio: versiones de vehículos, precios y fotos para estaciones de alquiler." },
      tech: { en: ["Seventeen vehicle versions with parameters, descriptions and 82 photos loaded into a CMS that has no import and no API, through scripted browser automation with a read-back after every save."],
              pl: ["Siedemnaście wersji pojazdów z parametrami, opisami i 82 zdjęciami wgrane do CMS-a bez importu i bez API, przez skryptową automatyzację przeglądarki z odczytem kontrolnym po każdym zapisie."],
              de: ["Siebzehn Fahrzeugversionen mit Parametern, Beschreibungen und 82 Fotos in ein CMS ohne Import und ohne API geladen, per skriptgesteuerter Browser-Automatisierung mit Kontrolle nach jedem Speichern."],
              fr: ["Dix-sept versions de véhicules avec paramètres, descriptions et 82 photos chargées dans un CMS sans import ni API, par automatisation scriptée du navigateur avec relecture après chaque enregistrement."],
              es: ["Diecisiete versiones de vehículos con parámetros, descripciones y 82 fotos cargadas en un CMS sin importación ni API, mediante automatización del navegador con lectura de control tras cada guardado."] } },
    { id: "kiokuya", name: "KIOKUYA", url: "https://kiokuya.com/", img: "kiokuya",
      sector: { en: "Own product: CRM for vehicle dealers", pl: "Własny produkt: CRM dla dealerów pojazdów", de: "Eigenes Produkt: CRM für Fahrzeughändler", fr: "Produit maison : CRM pour concessionnaires", es: "Producto propio: CRM para concesionarios" },
      what: { en: "Customer records, invoicing and fleet documents in one place, built in Python.",
              pl: "Klienci, faktury i dokumenty floty w jednym miejscu, napisane w Pythonie.",
              de: "Kundendaten, Rechnungen und Flottendokumente an einem Ort, in Python gebaut.",
              fr: "Fiches clients, facturation et documents de flotte au même endroit, écrit en Python.",
              es: "Fichas de clientes, facturación y documentos de flota en un solo lugar, hecho en Python." },
      tech: { en: ["Invoices with the vehicle identification number on each line, fleet invoices covering many vehicles, imports that de-duplicate themselves.", "A scheduler running in production on Postgres."],
              pl: ["Faktury z numerem VIN w każdej pozycji, faktury flotowe na wiele pojazdów, importy, które same się deduplikują.", "Harmonogram zadań działający produkcyjnie na Postgresie."],
              de: ["Rechnungen mit Fahrgestellnummer je Position, Flottenrechnungen über viele Fahrzeuge, Importe, die sich selbst deduplizieren.", "Ein Scheduler, der produktiv auf Postgres läuft."],
              fr: ["Factures avec le numéro de châssis sur chaque ligne, factures de flotte couvrant plusieurs véhicules, imports qui se dédoublonnent seuls.", "Un planificateur en production sur Postgres."],
              es: ["Facturas con el número de bastidor en cada línea, facturas de flota con muchos vehículos, importaciones que se deduplican solas.", "Un planificador en producción sobre Postgres."] } },
    { id: "kiodem", name: "kiodem.com", url: "https://seodemtechniczny-cpu.github.io/kiodem-site/", img: null,
      sector: { en: "This site", pl: "Ta strona", de: "Diese Website", fr: "Ce site", es: "Este sitio" },
      what: { en: "Hand-written HTML, CSS and JavaScript, no framework and no builder: an endless field of tiles in perspective, a loader in fifteen languages, five language versions and charts that draw themselves.",
              pl: "Ręcznie napisane HTML, CSS i JavaScript, bez frameworka i bez kreatora: nieskończone pole kafelków w perspektywie, loader w piętnastu językach, pięć wersji językowych i wykresy, które same się rysują.",
              de: "Handgeschriebenes HTML, CSS und JavaScript, ohne Framework und ohne Baukasten: ein endloses Kachelfeld in Perspektive, ein Loader in fünfzehn Sprachen, fünf Sprachversionen und Diagramme, die sich selbst zeichnen.",
              fr: "HTML, CSS et JavaScript écrits à la main, sans framework ni constructeur : un champ infini de tuiles en perspective, un chargement en quinze langues, cinq versions linguistiques et des graphiques qui se dessinent seuls.",
              es: "HTML, CSS y JavaScript escritos a mano, sin framework ni constructor: un campo infinito de fichas en perspectiva, una carga en quince idiomas, cinco versiones de idioma y gráficos que se dibujan solos." },
      tech: { en: ["Three files and one animation library; everything else is written by hand, which is why it can look like this and still load fast.", "Static hosting: nothing to update, nothing to break, nothing to pay for."],
              pl: ["Trzy pliki i jedna biblioteka do animacji; cała reszta napisana ręcznie, dlatego może tak wyglądać i wciąż szybko się ładować.", "Hosting statyczny: nic do aktualizowania, nic do zepsucia, nic do płacenia."],
              de: ["Drei Dateien und eine Animationsbibliothek; alles andere ist von Hand geschrieben, deshalb kann es so aussehen und trotzdem schnell laden.", "Statisches Hosting: nichts zu aktualisieren, nichts kann kaputtgehen, nichts zu bezahlen."],
              fr: ["Trois fichiers et une bibliothèque d'animation ; tout le reste est écrit à la main, c'est pourquoi le site peut ressembler à ça et charger vite quand même.", "Hébergement statique : rien à mettre à jour, rien à casser, rien à payer."],
              es: ["Tres archivos y una librería de animación; todo lo demás está escrito a mano, por eso puede verse así y aun así cargar rápido.", "Alojamiento estático: nada que actualizar, nada que romper, nada que pagar."] } }
  ];

  var SERVICES = [
    { id: "websites", title: { en: "Websites", pl: "Strony", de: "Websites", fr: "Sites web", es: "Webs" },
      line: { en: "Built to be found and to take an enquiry", pl: "Zbudowane, żeby dało się je znaleźć i zapytać", de: "Gebaut, um gefunden zu werden und Anfragen anzunehmen", fr: "Conçus pour être trouvés et recevoir une demande", es: "Hechas para que las encuentren y reciban consultas" },
      text: { en: "WordPress and WooCommerce builds, storefront work on Shopify, Shoper and Shopware, location pages for showrooms, page speed, and hand-written HTML, CSS and JavaScript when a site has to feel different, like this one.",
              pl: "Wdrożenia na WordPressie i WooCommerce, prace w sklepach na Shopify, Shoper i Shopware, strony lokalizacji dla salonów, szybkość, a także ręcznie pisane HTML, CSS i JavaScript, gdy strona ma wyglądać inaczej niż wszystkie, jak ta.",
              de: "WordPress- und WooCommerce-Umsetzungen, Arbeiten an Shops auf Shopify, Shoper und Shopware, Standortseiten für Ausstellungsräume, Ladezeit, und handgeschriebenes HTML, CSS und JavaScript, wenn eine Website anders wirken soll, wie diese hier.",
              fr: "Réalisations WordPress et WooCommerce, travail sur des boutiques Shopify, Shoper et Shopware, pages de localisation pour showrooms, vitesse, et HTML, CSS et JavaScript écrits à la main quand un site doit être différent, comme celui-ci.",
              es: "Desarrollos en WordPress y WooCommerce, trabajo en tiendas Shopify, Shoper y Shopware, páginas de ubicación para salas de exposición, velocidad, y HTML, CSS y JavaScript escritos a mano cuando una web tiene que sentirse distinta, como esta." } },
    { id: "seo", chart: "seo", title: { en: "SEO and local search", pl: "SEO i wyszukiwanie lokalne", de: "SEO und lokale Suche", fr: "SEO et recherche locale", es: "SEO y búsqueda local" },
      line: { en: "Found for what people actually type", pl: "Widoczne pod to, co ludzie naprawdę wpisują", de: "Gefunden für das, was Menschen wirklich eintippen", fr: "Trouvé pour ce que les gens tapent vraiment", es: "Visible por lo que la gente escribe de verdad" },
      text: { en: "Search is where a showroom, a clinic or a school gets most of its new enquiries. The work is unglamorous and it compounds: fix what stops Google from reading the site, write the pages people are looking for, keep the Business Profile alive.",
              pl: "Wyszukiwarka daje salonowi, klinice czy szkole większość nowych zapytań. Ta praca nie jest efektowna, ale się sumuje: usunąć to, co przeszkadza Google czytać stronę, napisać strony, których ludzie szukają, utrzymać wizytówkę przy życiu.",
              de: "Über die Suche kommen die meisten neuen Anfragen für einen Ausstellungsraum, eine Praxis oder eine Schule. Die Arbeit ist unspektakulär und summiert sich: beseitigen, was Google am Lesen hindert, die Seiten schreiben, nach denen Menschen suchen, das Unternehmensprofil lebendig halten.",
              fr: "La recherche apporte à un showroom, une clinique ou une école la majorité de ses nouvelles demandes. Le travail n'a rien de spectaculaire et il s'accumule : corriger ce qui empêche Google de lire le site, écrire les pages que les gens cherchent, garder la fiche Google vivante.",
              es: "La búsqueda es de donde una sala de exposición, una clínica o una escuela saca la mayoría de sus consultas nuevas. El trabajo no luce y se acumula: arreglar lo que impide a Google leer la web, escribir las páginas que la gente busca, mantener vivo el perfil de Google." },
      details: {
        en: ["Technical base first: indexing, sitemap, speed and Core Web Vitals, structured data, hreflang on two-language sites.", "One page per service and per location, with the address, hours, directions and real photos. No town pages that only swap the name.", "Google Business Profile kept current: categories, services, photos, posts, and an answer to every review.", "Search Console read every month. Queries with many impressions and few clicks are the pages to fix next.", "No promised positions and no bought links. The report shows queries, clicks and enquiries, not a ranking score."],
        pl: ["Najpierw podstawa techniczna: indeksowanie, mapa strony, szybkość i Core Web Vitals, dane strukturalne, hreflang przy dwóch językach.", "Osobna strona dla każdej usługi i lokalizacji, z adresem, godzinami, dojazdem i prawdziwymi zdjęciami. Bez podstron miast, które różnią się tylko nazwą.", "Wizytówka Google na bieżąco: kategorie, usługi, zdjęcia, wpisy i odpowiedź na każdą opinię.", "Search Console czytana co miesiąc. Zapytania z wieloma wyświetleniami i małą liczbą kliknięć to strony do poprawy w pierwszej kolejności.", "Bez obiecywania pozycji i bez kupowania linków. Raport pokazuje zapytania, kliknięcia i zapytania ofertowe, nie „wynik SEO”."],
        de: ["Zuerst die technische Basis: Indexierung, Sitemap, Ladezeit und Core Web Vitals, strukturierte Daten, hreflang bei zwei Sprachen.", "Eine Seite pro Leistung und pro Standort, mit Adresse, Öffnungszeiten, Anfahrt und echten Fotos. Keine Ortsseiten, die nur den Namen tauschen.", "Google-Unternehmensprofil aktuell: Kategorien, Leistungen, Fotos, Beiträge und eine Antwort auf jede Bewertung.", "Search Console jeden Monat gelesen. Anfragen mit vielen Einblendungen und wenigen Klicks sind die Seiten, die als Nächstes dran sind.", "Keine versprochenen Positionen und keine gekauften Links. Der Bericht zeigt Anfragen, Klicks und Kontaktanfragen, keinen SEO-Score."],
        fr: ["La base technique d'abord : indexation, sitemap, vitesse et Core Web Vitals, données structurées, hreflang pour les sites bilingues.", "Une page par prestation et par lieu, avec l'adresse, les horaires, l'itinéraire et de vraies photos. Pas de pages de villes qui ne changent que le nom.", "Fiche Google tenue à jour : catégories, prestations, photos, posts et une réponse à chaque avis.", "Search Console lue chaque mois. Les requêtes à beaucoup d'impressions et peu de clics désignent les pages à corriger en premier.", "Pas de positions promises ni de liens achetés. Le rapport montre les requêtes, les clics et les demandes, pas un score SEO."],
        es: ["Primero la base técnica: indexación, sitemap, velocidad y Core Web Vitals, datos estructurados, hreflang en webs bilingües.", "Una página por servicio y por ubicación, con dirección, horario, cómo llegar y fotos reales. Sin páginas de ciudades que solo cambian el nombre.", "Perfil de Google al día: categorías, servicios, fotos, publicaciones y respuesta a cada reseña.", "Search Console leída cada mes. Las búsquedas con muchas impresiones y pocos clics son las páginas que toca arreglar primero.", "Sin posiciones prometidas ni enlaces comprados. El informe muestra búsquedas, clics y consultas, no una puntuación SEO."] } },
    { id: "ads", chart: "ads", title: { en: "Google Ads", pl: "Google Ads", de: "Google Ads", fr: "Google Ads", es: "Google Ads" },
      line: { en: "Campaigns judged by enquiries, not clicks", pl: "Kampanie oceniane po zapytaniach, nie po kliknięciach", de: "Kampagnen, gemessen an Anfragen, nicht an Klicks", fr: "Des campagnes jugées aux demandes, pas aux clics", es: "Campañas juzgadas por consultas, no por clics" },
      text: { en: "A click is a cost. An enquiry is the point. Every account is set up so that the two can be told apart, by campaign, by location and by product, and the budget follows the enquiries.",
              pl: "Kliknięcie to koszt. Zapytanie to cel. Każde konto jest ustawione tak, żeby dało się je rozróżnić po kampanii, lokalizacji i produkcie, a budżet szedł za zapytaniami.",
              de: "Ein Klick ist ein Kostenpunkt. Eine Anfrage ist das Ziel. Jedes Konto ist so aufgebaut, dass sich beides unterscheiden lässt, nach Kampagne, Standort und Produkt, und das Budget den Anfragen folgt.",
              fr: "Un clic est un coût. Une demande est le but. Chaque compte est monté pour que l'on distingue les deux, par campagne, par lieu et par produit, et que le budget suive les demandes.",
              es: "Un clic es un coste. Una consulta es el objetivo. Cada cuenta se monta para distinguir ambos, por campaña, ubicación y producto, y para que el presupuesto siga a las consultas." },
      details: {
        en: ["Campaigns split by intent: brand, service plus town, generic. Each group gets its own budget and its own numbers.", "Search terms reviewed weekly. Irrelevant ones are excluded before they eat the budget.", "Conversions are enquiries: forms, calls, WhatsApp clicks and directions, counted once and by location.", "Budget follows impression share and enquiries per group, never clicks.", "Shopping and Merchant Center for shops: feed health, disapprovals, prices in step with the shop.", "A monthly note in plain words: what changed, what it did, what happens next."],
        pl: ["Kampanie podzielone według intencji: marka, usługa plus miasto, ogólne. Każda grupa ma własny budżet i własne liczby.", "Wyszukiwane frazy przeglądane co tydzień. Nietrafione wykluczane, zanim zjedzą budżet.", "Konwersje to zapytania: formularze, telefony, kliknięcia w WhatsApp i dojazd, liczone raz i po lokalizacji.", "Budżet idzie za udziałem w wyświetleniach i zapytaniami w grupie, nigdy za kliknięciami.", "Shopping i Merchant Center dla sklepów: kondycja feedu, odrzucenia, ceny zgodne ze sklepem.", "Co miesiąc notatka zwykłym językiem: co się zmieniło, co to dało, co dalej."],
        de: ["Kampagnen nach Absicht getrennt: Marke, Leistung plus Ort, generisch. Jede Gruppe bekommt ihr eigenes Budget und ihre eigenen Zahlen.", "Suchbegriffe wöchentlich geprüft. Unpassende werden ausgeschlossen, bevor sie das Budget fressen.", "Konversionen sind Anfragen: Formulare, Anrufe, WhatsApp-Klicks und Routenanfragen, einmal gezählt und nach Standort.", "Budget folgt dem Anteil an Einblendungen und den Anfragen je Gruppe, nie den Klicks.", "Shopping und Merchant Center für Shops: Feed-Zustand, Ablehnungen, Preise im Gleichschritt mit dem Shop.", "Monatlich eine Notiz in klaren Worten: was sich geändert hat, was es gebracht hat, was als Nächstes kommt."],
        fr: ["Campagnes séparées par intention : marque, prestation plus ville, générique. Chaque groupe a son budget et ses chiffres.", "Termes de recherche revus chaque semaine. Les hors-sujet sont exclus avant de manger le budget.", "Les conversions sont des demandes : formulaires, appels, clics WhatsApp et itinéraires, comptés une fois et par lieu.", "Le budget suit la part d'impressions et les demandes par groupe, jamais les clics.", "Shopping et Merchant Center pour les boutiques : santé du flux, refus, prix alignés sur la boutique.", "Une note mensuelle en mots simples : ce qui a changé, ce que ça a donné, la suite."],
        es: ["Campañas separadas por intención: marca, servicio más ciudad, genéricas. Cada grupo tiene su presupuesto y sus números.", "Términos de búsqueda revisados cada semana. Los que no encajan se excluyen antes de comerse el presupuesto.", "Las conversiones son consultas: formularios, llamadas, clics de WhatsApp y cómo llegar, contadas una vez y por ubicación.", "El presupuesto sigue a la cuota de impresiones y a las consultas por grupo, nunca a los clics.", "Shopping y Merchant Center para tiendas: salud del feed, rechazos, precios alineados con la tienda.", "Una nota mensual en palabras llanas: qué cambió, qué dio y qué viene después."] } },
    { id: "measurement", title: { en: "Measurement", pl: "Pomiar", de: "Messung", fr: "Mesure", es: "Medición" },
      line: { en: "Numbers that agree with each other", pl: "Liczby, które się ze sobą zgadzają", de: "Zahlen, die zueinander passen", fr: "Des chiffres qui concordent", es: "Números que cuadran entre sí" },
      text: { en: "GA4, Tag Manager and consent mode, Merchant Center and Search Console, set up so the shop, the ads and the reports count the same sale once. Return on ad spend is checked against paid orders, never read off a panel.",
              pl: "GA4, Tag Manager i tryb zgody, Merchant Center i Search Console, ustawione tak, żeby sklep, reklamy i raporty liczyły tę samą sprzedaż raz. Zwrot z reklam sprawdzany na opłaconych zamówieniach, nigdy odczytywany z panelu.",
              de: "GA4, Tag Manager und Consent Mode, Merchant Center und Search Console, so eingerichtet, dass Shop, Anzeigen und Berichte denselben Verkauf einmal zählen. Die Werbe-Rendite wird an bezahlten Bestellungen geprüft, nie vom Panel abgelesen.",
              fr: "GA4, Tag Manager et consent mode, Merchant Center et Search Console, réglés pour que la boutique, les annonces et les rapports comptent la même vente une fois. Le retour publicitaire est vérifié sur les commandes payées, jamais lu sur un panneau.",
              es: "GA4, Tag Manager y modo de consentimiento, Merchant Center y Search Console, configurados para que la tienda, los anuncios y los informes cuenten la misma venta una vez. El retorno publicitario se comprueba sobre pedidos pagados, nunca se lee de un panel." } },
    { id: "automation", title: { en: "Automation", pl: "Automatyzacje", de: "Automatisierung", fr: "Automatisation", es: "Automatización" },
      line: { en: "Small programs that run unattended", pl: "Małe programy, które działają bez nadzoru", de: "Kleine Programme, die unbeaufsichtigt laufen", fr: "De petits programmes qui tournent sans surveillance", es: "Pequeños programas que funcionan solos" },
      text: { en: "Python integrations: supplier feeds and stock, invoicing and CRM, price checks, monitoring and reports. Written for your setup, left with the code.",
              pl: "Integracje w Pythonie: feedy i stany hurtowni, faktury i CRM, sprawdzanie cen, monitoring i raporty. Pisane pod Twoje narzędzia, zostają z kodem.",
              de: "Python-Integrationen: Lieferanten-Feeds und Bestände, Rechnungen und CRM, Preisprüfungen, Monitoring und Berichte. Für Ihre Umgebung geschrieben, mit Quellcode übergeben.",
              fr: "Intégrations Python : flux et stocks fournisseurs, facturation et CRM, contrôle des prix, surveillance et rapports. Écrites pour votre installation, livrées avec le code.",
              es: "Integraciones en Python: feeds y stock de proveedores, facturación y CRM, control de precios, monitorización e informes. Escritas para tu entorno, entregadas con el código." } }
  ];

  var CHARTS = {
    ads: {
      title: { en: "Example account, one month: share of spend against share of enquiries", pl: "Przykładowe konto, jeden miesiąc: udział w wydatkach i udział w zapytaniach", de: "Beispielkonto, ein Monat: Anteil an Ausgaben gegen Anteil an Anfragen", fr: "Compte d'exemple, un mois : part des dépenses contre part des demandes", es: "Cuenta de ejemplo, un mes: cuota de gasto frente a cuota de consultas" },
      legend: { en: ["Share of spend", "Share of enquiries"], pl: ["Udział w wydatkach", "Udział w zapytaniach"], de: ["Anteil an Ausgaben", "Anteil an Anfragen"], fr: ["Part des dépenses", "Part des demandes"], es: ["Cuota de gasto", "Cuota de consultas"] },
      caption: { en: "The two bars should look alike. Where spend outruns enquiries, budget moves to the rows above.", pl: "Oba słupki powinny wyglądać podobnie. Tam, gdzie wydatki wyprzedzają zapytania, budżet przechodzi do wierszy wyżej.", de: "Beide Balken sollten sich ähneln. Wo die Ausgaben den Anfragen davonlaufen, wandert Budget in die Zeilen darüber.", fr: "Les deux barres devraient se ressembler. Là où la dépense dépasse les demandes, le budget remonte vers les lignes du dessus.", es: "Las dos barras deberían parecerse. Donde el gasto supera a las consultas, el presupuesto sube a las filas de arriba." },
      words: { en: ["of spend", "of enquiries"], pl: ["wydatków", "zapytań"], de: ["der Ausgaben", "der Anfragen"], fr: ["des dépenses", "des demandes"], es: ["del gasto", "de las consultas"] },
      rows: [
        { label: { en: "Service + town", pl: "Usługa + miasto", de: "Leistung + Ort", fr: "Prestation + ville", es: "Servicio + ciudad" }, a: 22, b: 46 },
        { label: { en: "Brand", pl: "Marka", de: "Marke", fr: "Marque", es: "Marca" }, a: 8, b: 24 },
        { label: { en: "Generic", pl: "Ogólne", de: "Generisch", fr: "Génériques", es: "Genéricos" }, a: 31, b: 22 },
        { label: { en: "Competitor names", pl: "Nazwy konkurencji", de: "Wettbewerbernamen", fr: "Noms de concurrents", es: "Nombres de competidores" }, a: 14, b: 5 },
        { label: { en: "Irrelevant", pl: "Nietrafione", de: "Unpassend", fr: "Hors sujet", es: "Fuera de tema" }, a: 25, b: 3 }
      ]
    },
    seo: {
      title: { en: "Example Search Console, one month: impressions per query", pl: "Przykładowa Search Console, jeden miesiąc: wyświetlenia na zapytanie", de: "Beispiel Search Console, ein Monat: Einblendungen je Suchanfrage", fr: "Exemple de Search Console, un mois : impressions par requête", es: "Search Console de ejemplo, un mes: impresiones por búsqueda" },
      legend: { en: ["Impressions", "Many impressions, few clicks: fix this page next"], pl: ["Wyświetlenia", "Dużo wyświetleń, mało kliknięć: ta strona do poprawy"], de: ["Einblendungen", "Viele Einblendungen, wenige Klicks: diese Seite zuerst"], fr: ["Impressions", "Beaucoup d'impressions, peu de clics : page à corriger"], es: ["Impresiones", "Muchas impresiones, pocos clics: esta página primero"] },
      caption: { en: "Hover a row for clicks, click-through rate and average position.", pl: "Najedź na wiersz, żeby zobaczyć kliknięcia, CTR i średnią pozycję.", de: "Zeile berühren für Klicks, Klickrate und mittlere Position.", fr: "Survolez une ligne pour les clics, le taux de clic et la position moyenne.", es: "Pasa por una fila para ver clics, CTR y posición media." },
      words: { en: ["impressions", "clicks", "position"], pl: ["wyświetleń", "kliknięć", "pozycja"], de: ["Einblendungen", "Klicks", "Position"], fr: ["impressions", "clics", "position"], es: ["impresiones", "clics", "posición"] },
      rows: [
        { label: { en: "kitchens gliwice", pl: "kuchnie gliwice", de: "küchen gliwice", fr: "cuisines gliwice", es: "cocinas gliwice" }, imp: 1240, clicks: 61, pos: 3.1 },
        { label: { en: "kitchen showroom silesia", pl: "salon kuchni śląsk", de: "küchenstudio schlesien", fr: "showroom cuisine silésie", es: "exposición cocinas silesia" }, imp: 980, clicks: 9, pos: 8.4 },
        { label: { en: "fitted kitchens price", pl: "kuchnie na wymiar cena", de: "einbauküche preis", fr: "cuisine sur mesure prix", es: "cocina a medida precio" }, imp: 860, clicks: 38, pos: 4.0 },
        { label: { en: "german kitchens", pl: "kuchnie niemieckie", de: "deutsche küchen", fr: "cuisines allemandes", es: "cocinas alemanas" }, imp: 720, clicks: 5, pos: 9.1 },
        { label: { en: "kitchen design consultation", pl: "projekt kuchni konsultacja", de: "küchenplanung beratung", fr: "conception cuisine conseil", es: "diseño de cocina asesoría" }, imp: 410, clicks: 27, pos: 2.6 },
        { label: { en: "kitchen showroom opening hours", pl: "salon kuchni godziny otwarcia", de: "küchenstudio öffnungszeiten", fr: "showroom cuisine horaires", es: "exposición cocinas horario" }, imp: 300, clicks: 2, pos: 6.8 }
      ]
    }
  };

  var GREETINGS = ["Welcome", "Witamy", "Willkommen", "Bienvenue", "Bienvenido", "Benvenuti", "Välkommen",
    "Welkom", "Bem-vindo", "Vítejte", "Tervetuloa", "ようこそ", "환영합니다", "Καλώς ήρθατε", "Ласкаво просимо"];
  var GREETING_BY_LANG = { en: "Welcome", pl: "Witamy", de: "Willkommen", fr: "Bienvenue", es: "Bienvenido" };
  var LOCALES = { en: "en-GB", pl: "pl-PL", de: "de-DE", fr: "fr-FR", es: "es-ES" };

  return { LANGS: LANGS, I18N: I18N, WORK: WORK, SERVICES: SERVICES, CHARTS: CHARTS,
           GREETINGS: GREETINGS, GREETING_BY_LANG: GREETING_BY_LANG, LOCALES: LOCALES };
})();
